### ISSUE TITLE
400 when saving note

### ISSUE THREAD

**Issue by paymog** [kwypchlo/skydb-example#5] opened 2021-08-08 16:58 UTC
I get a 400 when I try to save a note on https://siasky.net/_BlCbtTG_OiNCDjxQ38ugC6-1eED5cTeMBDN4LJbkABj7Q/

![image](https://user-images.githubusercontent.com/1986950/128639546-ad0b7c55-48b6-4032-8f60-1719155fd4ad.png)

Is this expected?

**Comment by interstella-5555** [comment] 2021-08-09 09:25
thank you for reporting the issue - we're currently having performance issues on the siasky.net portal due to increased traffic, we're improving the infrastructure and it should resolve the issues you're having

**Comment by mrcnski** [comment] 2021-08-09 15:47
The 400 error is `Unable to update the registry: provided revision number is invalid` which looks like a bug in the skapp. @kwypchlo

**Comment by dghelm** [comment] 2021-08-09 16:47
As far as I can tell, this is just an effect of trying to read/write `v2` SkyDB entries using an out-of-date `skynet-js` version. This is expected behavior, where the newer versions can read older version data, but not vice-versa.

Behavior should be correct at https://note-to-self.hns.siasky.net/

@paymog Can I ask where you found this URL? Seems like we need to hunt down some out-of-date documentation.

**Comment by paymog** [comment] 2021-08-10 16:59
Unfortunately I don't remember where I found that link ☹️

**Comment by interstella-5555** [comment] 2021-09-29 12:38
I think we can close this, referenced version is outdated and a current one from https://note-to-self.hns.siasky.net should be used

**Closed as completed by interstella-5555** 2021-09-29 12:38 UTC
